version: 2.1
jobs:
  build:
    docker:
      - image: maven:3-jdk-8-alpine
    steps:
      - checkout
      - restore_cache:
          key: spring-boot-starter-spigot-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: spring-boot-starter-spigot-{{ checksum "pom.xml" }}
      - run: mvn clean test jacoco:report coveralls:report -Dcoveralls.token=$COVERALLS_TOKEN -o